---
title: "Best-Fit-For-Me"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    social: menu
    source_code: embed
    theme: yeti
    navbar:
      - { title: "About", href: "https://www.franchisecost.com/", align: right }
runtime: shiny
---


```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
packages <- c("dplyr","ggplot2","flexdashboard","data.table","tibble", "DT", "mltools", "rmarkdown") 
lapply(packages, library, character.only = TRUE)
rm(packages)

setwd("/srv/shiny-server/BestFit4Me")
dataset <- read.csv("./data/franchiseProfilesbyGMsDec5.csv", header = TRUE) %>% dplyr::select(-starts_with("X"))

#define Tanimoto helper function
tanimoto <- function(x, similarity=F) {
  res<-sapply(x, function(x1){
    sapply(x, function(x2) {i=length(which(x1 & x2)) / length(which(x1 | x2)); ifelse(is.na(i), 0, i)})
  })
  if(similarity==T) return(res)
  else return(1-res)
}

```

```{r}
defaultQues <- c("Select one")
ques1 <- factor(unique(levels(dataset$B2BorC)))
ques2 <- factor(unique(levels(dataset$InOrOut)))
ques3 <- factor(unique(levels(dataset$StoreVehicleHome)))
ques4 <- factor(unique(levels(dataset$EmployeeCount)))
ques5 <- factor(unique(levels(dataset$PartSeasonalOrFullTime)))
ques6 <- factor(unique(levels(dataset$ProductSalesOrServices)))
ques7 <- factor(unique(levels(dataset$WorkSchedule)))
ques8 <- factor(unique(levels(dataset$VeteranFriendly)))
ques9 <- factor(unique(levels(dataset$ZorProvideLeads)))
```

# Personalize Your Franchise Choice
## Question Set 1
Top variable contributors to Key Dim 1-2
```{r}
selectInput(
  inputId = "VeteranFriendly",
  'How important are veteran advantaged franchise programs to you?',
  c("", as.character(levels(ques8)))
)

selectInput(
  inputId = "PartSeasonalOrFullTime",
  'How much time are you planning to dedicate to your franchise?',
  c("", as.character(levels(ques5)))
)


selectInput(
  inputId = "WorkSchedule",
  'How many hours per week do you want to allocate to your franchise?',
  c("", as.character(levels(ques7)))
)
```

## Question Set 2
Top variable contributors to Key Dim 1-2
```{r}
selectInput(
  inputId = "EmployeeCount",
  'How large a team do you prefer working with?',
  c("", as.character(levels(ques4)))
)

selectInput(
  inputId = "ProductSalesOrServices",
  'Do you prefer product sales or providing services? ',
  c("", as.character(levels(ques6)))
  )

selectInput(inputId = "ZorProvideLeads",
            'Do you prefer to generate your own customers or rely on the franchisor?',
            c("", as.character(levels(ques9)))
)
```

```{r}
renderGauge({
  rate <- df6()$RelevanceScore[1]
  gauge(rate, min = 0, max = 100, symbol = '%', label = "Your Best Fit Score", gaugeSectors(
    success = c(50, 100), warning = c(30, 49), danger = c(0, 29)
  ))
})

actionButton("clickMe", label = "Click 4 Best Fit", class = "btn btn-lg btn-primary", width = 200, onclick="location.href='#section-visualize-your-results';")
```


## Question Set 3
Variable non-contributors to Key Dim 1-2
```{r}
selectInput(inputId = "StoreVehicleHome",
  'Where would you prefer to conduct business with customers?',
  c("", as.character(levels(ques3)))
)

selectInput(
  inputId = "B2BorC",
  'Would you rather serve businesses or consumers?',
  c("", as.character(levels(ques1)))
)

selectInput(inputId = "InOrOut",
            'Would you prefer to be indoors or outdoors?',
            c("", as.character(levels(ques2)))
)
```


```{r, results='hide'}
# Display User Data plus List of Active Franchises
# Prospect Preference Profile
df1 <-
  reactive({
    data.frame(
      input$B2BorC,
      input$InOrOut,
      input$StoreVehicleHome,
      input$EmployeeCount,
      input$PartSeasonalOrFullTime,
      input$ProductSalesOrServices,
      input$WorkSchedule,
      input$VeteranFriendly,
      input$ZorProvideLeads
     )  
  })

df1_new <- reactive({
  d <- df1() %>% mutate("Company Name" = "TestUser", RevGrp = " ",Site_ID = " ")
  colnames(d) <- c(
    "B2BorC",
    "InOrOut",
    "StoreVehicleHome",
    "EmployeeCount",
    "PartSeasonalOrFullTime",
    "ProductSalesOrServices",
    "WorkSchedule",
    "VeteranFriendly",
    "ZorProvideLeads",
    "Company Name",
    "RevGrp",
    "Site_ID"
  )
  d[,c(10, 1:9)] %>% tibble::column_to_rownames(var = "Company Name")
})

DT::renderDataTable(df1_new())
```

```{r, results='hide'}
# Profiles of Active Franchises
## Input Data Table

#Exclude rows with all zeroes, and assign row names
df2 <- reactive({
  df_temp <- dataset %>% tibble::column_to_rownames(var = "Company.Name")
    df_temp[1:382,3:11]
  })

DT::renderDataTable(df2())
```

```{r, results='hide'}
# Resulting Table
## Append tables
df3 <- reactive({
  test <- rbind(df1_new(), df2())
  
})
DT::renderDataTable(df3())
```

```{r, results='hide'}
# Resulting Table 2 for One-hot encoding
df4 <- reactive({
  testagain <- as.data.frame(mltools::one_hot(as.data.table(df3())))
  rownames(testagain) <- rownames(df3())
  testagain
})
DT::renderDataTable(df4())
```

# Visualize Your Results
## Top Recomendations 
```{r}
#Initialize a similarity/dissimilarity matrix as input Tanimoto similarity calculation
df5 <- reactive({
  testboo <- as.matrix(df4())
  rownames(testboo) <- rownames(df4())
  colnames(testboo) <- colnames(df4())
  testboo
})

df6 <- reactive({
  testbooboo <- t(df5())
  colnames(testbooboo) <- rownames(df5())
  testbooboo <- data.frame(testbooboo)
  sim.jac2 <- round(tanimoto(testbooboo,T)*100,2)
  rownames(sim.jac2) <- rownames(df5())
  colnames(sim.jac2) <- rownames(df5())
  finally <- as.data.frame(sim.jac2) %>% dplyr::select(starts_with("TestUser")) %>% tibble::rownames_to_column() %>% arrange(desc(TestUser)) %>% dplyr::filter(rowname != "TestUser") %>% top_n(25, TestUser)
colnames(finally) <- c("CompanyName", "RelevanceScore")
  finally
})
DT::renderDataTable(df6())
```

### Do it Again?
```{r}
renderGauge({
  rate <- df6()$RelevanceScore[1]
  gauge(rate, min = 0, max = 100, symbol = '%', label = "Your Best Fit Score", gaugeSectors(
    success = c(50, 100), warning = c(30, 49), danger = c(0, 29)
  ))
})

df8 <- reactive({
  newtest <- df6() %>% mutate(from = "Test User", to = CompanyName, weight = RelevanceScore) %>% dplyr::select(-starts_with("CompanyName"),-starts_with("RelevanceScore"))
  newtest
})
#DT::renderDataTable(df8())

```


```{r}
prnt.test <- function(x){
   cat(x, sep="\n\n")
}
prnt.test(c(" ", " "))

actionButton("clickMe2", label = "Refine Answers", class = "btn btn-lg btn-primary", width = 200,
             onclick="location.href='#section-personalize-your-franchise-choice';")
```